cabal-version:      2.4
name:               haskan2
version:            0.1.0.0

-- A short (one-line) description of the package.
-- synopsis:

-- A longer description of the package.
-- description:

-- A URL where users can report bugs.
-- bug-reports:

-- The license under which the package is released.
-- license:
author:             Omg Bebebe
maintainer:         omgbebebe@gmail.com

-- A copyright notice.
-- copyright:
-- category:
extra-source-files: CHANGELOG.md

library
    exposed-modules:  Graphics.Haskan
                       Graphics.Haskan.Assets
                       Graphics.Haskan.Assets.Cache
                       Graphics.Haskan.Assets.InternalFormat
                       Graphics.Haskan.Assets.TexturePreprocessor
                       Graphics.Haskan.BoundingBox
                       Graphics.Haskan.Logger
                         Graphics.Haskan.Camera
                         Graphics.Haskan.Camera.Types
                         Graphics.Haskan.Camera.Orbital
                         Graphics.Haskan.Camera.Fly
                         Graphics.Haskan.DayNight
                        Graphics.Haskan.HosekWilkie
                        Graphics.Haskan.Debug.Server
                       Graphics.Haskan.Events
                        Graphics.Haskan.Engine
                         Graphics.Haskan.Engine.Capabilities.Clock
                         Graphics.Haskan.Engine.Capabilities.Graphics
                         Graphics.Haskan.Engine.Capabilities.Log
                         Graphics.Haskan.Engine.Capabilities.StateReader
                         Graphics.Haskan.Engine.Capabilities.Telemetry
                        Graphics.Haskan.Engine.Types
                       Graphics.Haskan.Engine.Scene
                        Graphics.Haskan.Engine.Update
                        Graphics.Haskan.Engine.Physics
                        Graphics.Haskan.Engine.Render
                        Graphics.Haskan.Engine.Render.Internal.FramePrepare
                        Graphics.Haskan.Engine.Render.Internal.FrameState
                        Graphics.Haskan.Engine.Render.Internal.PassRecording
                        Graphics.Haskan.Engine.Render.Internal.Setup
                        Graphics.Haskan.Engine.Render.Internal.Screenshot
                       Graphics.Haskan.Input
                       Graphics.Haskan.Resources
                       Graphics.Haskan.Vertex
                       Graphics.Haskan.Window
                       Graphics.Haskan.Mesh
                       Graphics.Haskan.Face
                       Graphics.Haskan.Model
                       Graphics.Haskan.Utils.ObjLoader
                       Graphics.Haskan.Utils.PieLoader
                       Graphics.Haskan.Utils.TangentSpace
                        Graphics.Haskan.UI.Backend
                        Graphics.Haskan.Vulkan.BRDF
                        Graphics.Haskan.Vulkan.Buffer
                       Graphics.Haskan.Vulkan.CommandBuffer
                       Graphics.Haskan.Vulkan.CommandPool
                       Graphics.Haskan.Vulkan.ComputePipeline
                       Graphics.Haskan.Vulkan.DeferredResources
                        Graphics.Haskan.Vulkan.DescriptorSet
                        Graphics.Haskan.Vulkan.DescriptorSetLayout
                        Graphics.Haskan.Vulkan.DescriptorSetLayout.TH
                        Graphics.Haskan.Vulkan.DescriptorPool
                       Graphics.Haskan.Vulkan.Device
                       Graphics.Haskan.Vulkan.DeviceCapabilities
                       Graphics.Haskan.Vulkan.Fence
                       Graphics.Haskan.Vulkan.Framebuffer
                       Graphics.Haskan.Vulkan.GraphicsPipeline
                       Graphics.Haskan.Vulkan.ImageView
                       Graphics.Haskan.Vulkan.Instance
                       Graphics.Haskan.Vulkan.Memory
                       Graphics.Haskan.Vulkan.PipelineLayout
                       Graphics.Haskan.Vulkan.PhysicalDevice
                       Graphics.Haskan.Vulkan.RenderPass
                       Graphics.Haskan.Vulkan.Render
                       Graphics.Haskan.Vulkan.ShaderModule
                          Graphics.Haskan.Vulkan.Shaders.Texture
                          Graphics.Haskan.Vulkan.Shaders.Wireframe
                          Graphics.Haskan.Vulkan.Shaders.EntityData
                         Graphics.Haskan.Vulkan.Shaders.LightData
                         Graphics.Haskan.Vulkan.Shaders.TH
                         Graphics.Haskan.Vulkan.Shaders.Compile
                         Graphics.Haskan.Vulkan.Shaders.Compute.Test
                        Graphics.Haskan.Vulkan.Shaders.Compute.Cull
                         Graphics.Haskan.Vulkan.Shaders.Compute.RadianceGen
                         Graphics.Haskan.Vulkan.Shaders.Compute.IrradianceGen
                           Graphics.Haskan.Vulkan.Shaders.Compute.CloudNoiseGen,
                           Graphics.Haskan.Vulkan.Shaders.Compute.CloudNoiseMipGen,
                           Graphics.Haskan.Vulkan.Shaders.Compute.CloudDetailNoiseGen,
                          Graphics.Haskan.Vulkan.Shaders.Compute.WeatherMapGen
                          Graphics.Haskan.Vulkan.Shaders.Compute.APVolume,
                          Graphics.Haskan.Vulkan.Shaders.Compute.APVolumeUniforms
                         Graphics.Haskan.Vulkan.Shaders.Deferred.GBuffer,
                         Graphics.Haskan.Vulkan.Shaders.Deferred.Lighting,
                         Graphics.Haskan.Vulkan.Shaders.Deferred.LightingProcedural,
                         Graphics.Haskan.Vulkan.Shaders.Deferred.Clouds,
                          Graphics.Haskan.Vulkan.Shaders.Deferred.GodRays,
                          Graphics.Haskan.Vulkan.Shaders.Forward.SimpleForward,
                        Graphics.Haskan.Vulkan.Semaphore
                       Graphics.Haskan.Vulkan.Swapchain
                       Graphics.Haskan.Vulkan.Texture
                       Graphics.Haskan.Vulkan.Types
                       Graphics.Haskan.Vulkan.Resources
                       Graphics.Haskan.Vulkan.VertexFormat
                        Graphics.Haskan.Debug.FrameInspector
                        Graphics.Haskan.Debug.Interface
                        Graphics.Haskan.Debug.Screenshot
                       Graphics.Haskan.Scene.ECS
                       Graphics.Haskan.Scene.Transform
                       Graphics.Haskan.Scene.GLTF
                        Graphics.Haskan.Render.RenderSystem
                        Graphics.Haskan.Render.Graph
                        Graphics.Haskan.Render.Deferred
                        Graphics.Haskan.Render.Forward
                        Graphics.Haskan.Render.ShaderProgram
                        Graphics.Haskan.Physics.Jolt.FFI
                        Graphics.Haskan.Physics.Jolt.Types
                        Graphics.Haskan.Physics.Jolt.World
 
    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:
    build-depends:    base >=4.17 && <4.24
                     , bytestring >=0.11 && <0.13
                     , clock >=0.7 && <0.9
                     , containers >=0.6 && <0.8
                     , stm >=2.5 && <2.6
                     , text >=2.0 && <2.2
                     , text-short >=0.1 && <0.2
                     , fast-logger >=3.0 && <3.4
                     , vulkan-api >=1.4.0 && <1.4.1
                     , vulkan >=3.0 && <4.0
                      , managed >=1.0 && <1.1
                      , sdl2 >=2.5 && <2.6
                      , dear-imgui >=2.4 && <2.5
                      , lens >=5.0 && <5.5
                     , linear >=1.23 && <1.24
                     , JuicyPixels >=3.3 && <3.4
                     , unordered-containers >=0.2 && <0.3
                     , vector >=0.13 && <0.14
                      -- for vulkan
                      , contravariant >=1.5 && <1.6
                       , effectful >=2.6 && <2.7
                       , fir
                      , template-haskell
                      , megaparsec >=9.5 && <9.8
                     , scientific >=0.3 && <0.4
                     , hashable >=1.3 && <1.7
                     , directory >=1.3 && <1.4
                      , filepath >=1.4 && <1.6
                      , time >=1.11 && <1.16
                      , aeson >=2.0 && <2.3
                      , network >=3.1 && <3.3
                       , half >=0.3 && <0.4
                       , optparse-applicative >=0.18 && <0.20
                        , mtl >=2.3 && <2.4
                        , random >=1.2 && <1.4
                         , gltf-loader >=0.3 && <0.4
    hs-source-dirs:   src
    extra-libraries:  jolt_wrapper
    default-language: GHC2021
    default-extensions:
                      OverloadedStrings
                      DataKinds
                      BlockArguments
                      LambdaCase

executable haskan2
    if os(windows)
      ghc-options:         -optl-mconsole -O2 -threaded
    else
      ghc-options:         -O2 -threaded

    main-is:          Main.hs

    -- Modules included in this executable, other than Main.
    -- other-modules:

    -- LANGUAGE extensions used by modules in this package.
    -- other-extensions:
    build-depends:    base >=4.17 && <4.24
                     , haskan2
                     , optparse-applicative >=0.18 && <0.20
                     , text >=2.0 && <2.2
    hs-source-dirs:   app
    default-language: GHC2021
    default-extensions:
                      OverloadedStrings

executable example1
    if os(windows)
      ghc-options:         -optl-mconsole -O2 -threaded
    else
      ghc-options:         -O2 -threaded

    main-is:          Main.hs

    build-depends:    base >=4.17 && <4.24
                     , haskan2
                     , linear >=1.23 && <1.24
    hs-source-dirs:   examples/example1
    default-language: GHC2021
    default-extensions:
                      OverloadedStrings

test-suite haskan2-test
    type:               exitcode-stdio-1.0
    main-is:            Tests.hs
    hs-source-dirs:     test
    other-modules:      Graphics.Haskan.Engine.Capabilities.Test
    build-depends:      base >=4.17 && <4.24
                     , haskan2
                     , tasty
                     , tasty-hunit
                     , mtl >=2.3 && <2.4
                     , text >=2.0 && <2.2
                     , vulkan-api >=1.4.0 && <1.4.1
                     , linear >=1.23 && <1.24
                     , lens >=5.0 && <5.5
                     , clock >=0.7 && <0.9
    default-language:  GHC2021
    default-extensions:
                       OverloadedStrings
